/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FTP_H_RPCGEN
#define _FTP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct file {
	char *file_name;
	char type;
};
typedef struct file file;

struct file_content {
	int fd;
	char content;
};
typedef struct file_content file_content;

#define ftp_program 0x23451111
#define ftp_vers 1

#if defined(__STDC__) || defined(__cplusplus)
#define openFile 1
extern  int * openfile_1(file *, CLIENT *);
extern  int * openfile_1_svc(file *, struct svc_req *);
#define appendContent 2
extern  int * appendcontent_1(file_content *, CLIENT *);
extern  int * appendcontent_1_svc(file_content *, struct svc_req *);
#define readContent 3
extern  char * readcontent_1(int *, CLIENT *);
extern  char * readcontent_1_svc(int *, struct svc_req *);
#define closeFile 4
extern  int * closefile_1(int *, CLIENT *);
extern  int * closefile_1_svc(int *, struct svc_req *);
extern int ftp_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define openFile 1
extern  int * openfile_1();
extern  int * openfile_1_svc();
#define appendContent 2
extern  int * appendcontent_1();
extern  int * appendcontent_1_svc();
#define readContent 3
extern  char * readcontent_1();
extern  char * readcontent_1_svc();
#define closeFile 4
extern  int * closefile_1();
extern  int * closefile_1_svc();
extern int ftp_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_file (XDR *, file*);
extern  bool_t xdr_file_content (XDR *, file_content*);

#else /* K&R C */
extern bool_t xdr_file ();
extern bool_t xdr_file_content ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FTP_H_RPCGEN */
