/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ftp.h"

bool_t
xdr_file (XDR *xdrs, file *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->file_name, 255))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->type))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_content (XDR *xdrs, file_content *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->content))
		 return FALSE;
	return TRUE;
}
